// backend/models/ContentTask.js
const mongoose = require('mongoose');

const ContentTaskSchema = new mongoose.Schema({
  title: {
    type: String,
    required: [true, 'Please add a content title or topic'],
    trim: true
  },
  associatedType: {
    type: String,
    required: true,
    enum: ['DSA', 'Project', 'General'],
    default: 'General'
  },
  // Optional reference to see exactly which project this content stems from (e.g., PageFlow)
  relatedProjectName: {
    type: String,
    default: '',
    trim: true
  },
  contentType: {
    type: String,
    required: true,
    enum: ['Shorts', 'Long Form'],
    default: 'Long Form'
  },
  status: {
    type: String,
    required: true,
    enum: ['Planned', 'Processing', 'Completed'],
    default: 'Planned'
  },
  // Tracks your n8n / ChatGPT asset engine outputs
  aiMetadata: {
    thumbnailUrl: {
      type: String,
      default: '' // Will save the cloud URL of the image ChatGPT generates
    },
    generatedScriptOutline: {
      type: String,
      default: '' // Holds the text block generated by your AI worker
    },
    triggeredAt: {
      type: Date
    }
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model('ContentTask', ContentTaskSchema);